name: Check Prettier format
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
    - name: Prettier Check
      uses: rutajdash/prettier-cli-action@v1.0.0
