name: Check Prettier format
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: actionsx/prettier
        uses: actionsx/prettier@v2
        with:
          # Prettier CLI arguments
          args: --config  .prettierrc.json --check .
